# MPO 624: Assignment for Maximum Covariance Analysis
#### Becca Hammersla
#### 4/25/18

## 1.2 (a)

In [1]:
import numpy as np
from netCDF4 import Dataset

In [2]:
#create matrix
m = np.array([[1,2], [3,4], [5,6]])
print(m)

[[1 2]
 [3 4]
 [5 6]]


In [3]:
#calculate left, right, singular value matrix
u,s,vt = np.linalg.svd(m)
print('u =', u); print ('')
print('s =', s); print ('')
print('vt = ', vt); print ('')

u = [[-0.2298477   0.88346102  0.40824829]
 [-0.52474482  0.24078249 -0.81649658]
 [-0.81964194 -0.40189603  0.40824829]]

s = [9.52551809 0.51430058]

vt =  [[-0.61962948 -0.78489445]
 [-0.78489445  0.61962948]]



In [4]:
#reconstruct data
smat=np.zeros([3,2])
smat[0:2,0:2]=np.diag(s)
n = np.matmul(u,np.matmul(smat,vt))
print(n)

[[1. 2.]
 [3. 4.]
 [5. 6.]]


## 1.2 (b)

In [5]:
#2x2 and 3x3 covariance matrices: eigen method
a = np.array([[7,5],[10,6]])
am = np.mean(a,1)
ap = a-np.array([[am[0]],[am[1]]])
aeig = np.matmul(ap,ap.transpose())
print('2x2 Eigen method = \n', aeig);print('')

b = np.array([[2,4,6],[5,10,3],[3,6,9]])
bm = np.mean(b,1)
bp = b-np.array([[bm[0]],[bm[1]],[bm[2]]])
beig = np.matmul(bp,bp.transpose())
print('3x3 Eigen method = \n', beig);print('')







2x2 Eigen method = 
 [[2. 4.]
 [4. 8.]]

3x3 Eigen method = 
 [[ 8. -4. 12.]
 [-4. 26. -6.]
 [12. -6. 18.]]



In [6]:
#2x2 and 3x3 covariance matrices: SVD method

In [7]:
u,s,vt=np.linalg.svd(ap)
SM=np.zeros([2,2])
SM[0:2,0:2]=np.diag(s)
T=np.matmul(u,SM);T1=np.matmul(SM.transpose(),u.transpose());
RM1=np.matmul(T,T1)
print('2x2 SVD method = \n',RM1);print('')

u,s,vt=np.linalg.svd(bp)
SM=np.zeros([3,3])
SM[0:3,0:3]=np.diag(s)
T=np.matmul(u,SM);T2=np.matmul(SM.transpose(),u.transpose());
RM=np.matmul(T,T2)
print('3x3 SVD method = \n',RM)

2x2 SVD method = 
 [[2. 4.]
 [4. 8.]]

3x3 SVD method = 
 [[ 8. -4. 12.]
 [-4. 26. -6.]
 [12. -6. 18.]]


In [8]:
# covariance
ac = np.cov(a)
bc = np.cov(b)

EVAL,EVEC=np.linalg.eig(bc);
bcc=np.matmul(np.matmul(EVEC,np.diag(EVAL)),np.linalg.inv(EVEC))
print('cov matrix = \n',bcc)

cov matrix = 
 [[ 4. -2.  6.]
 [-2. 13. -3.]
 [ 6. -3.  9.]]


In [9]:
# DTD
EVAL,EVEC=np.linalg.eig(np.matmul(bp.transpose(),bp));
bcc=np.matmul(np.matmul(EVEC,np.diag(EVAL)),np.linalg.inv(EVEC))
print ('DTD = \n',np.matmul(bp.transpose(),bp))
print('Cov matrix = \n',bcc)

DTD = 
 [[ 14.  -4. -10.]
 [ -4.  16. -12.]
 [-10. -12.  22.]]
Cov matrix = 
 [[ 14.  -4. -10.]
 [ -4.  16. -12.]
 [-10. -12.  22.]]


The eigen method can only be used with a square matrix because there needs to be a diagonal of eigenvalues. Non-square matrices do not have diagonals. This is why the SVD is used for non-diagonal matrices (like our 3x2) and was able to return 3 matrices. 

When using a 2x2 matrix, the DDT and SVD returns are equal, but they are double in a 3x3 matrix. We must multiply the DDT by 1/N-1 in order to return the correct covariance matrix. 

In order to reconstruct a full dataset, DTD is necessary. 